services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    container_name: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name:  pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '5050:80'
    depends_on:
      - db
  app:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name:  server
    environment:
      # - PORT=${PORT} // variable 
      - PORT=8000
      - PG_HOST=postgres
      - PG_PORT=5432
      - PG_USER=postgres
      - PG_PASS=postgres
      - PG_NAME=postgres
      - ORIGIN=http://localhost:8000,http://localhost:3001,https://localhost:3001,https://localhost
      - COOKIE_KEY=school
      - JWT_SECRET=school
    ports:
      - '8000:8000'
    depends_on:
      - db
    volumes:
      - ./server/src:/app/src
      
  web:
      build:
        context: ./web
        dockerfile: Dockerfile
      container_name:  web
      environment:
        - NEXT_PUBLIC_BASE_URL=http://host.docker.internal:3001
        - NEXT_PUBLIC_COOKIE_KEY=school
        - NEXT_PUBLIC_JWT_SECRET=school
      ports:
        - '3001:3001'
      depends_on:
        - app
      volumes:
        - ./web/src:/app/src
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: nginx:latest
    container_name: nginx
    ports:
      - "443:443"
      - "80:80"
    restart: always
    volumes:
      - ./nginx/nginx-selfsigned.crt:/etc/nginx/ssl/nginx-selfsigned.crt
      - ./nginx/nginx-selfsigned.key:/etc/nginx/ssl/nginx-selfsigned.key
    depends_on:
      - web
      - app