import type { Metadata } from 'next';
import './globals.css';
import React from 'react';

export const metadata: Metadata = {
  title: 'Rezaul Karim',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: Readonly<{children: React.ReactNode}>) {
  return (
    <html lang="en">
      <body
        className="antialiased flex justify-center"
      >
        {children}
      </body>
    </html>
  );
}
